2022-04-06 15:18:13,987 - main - INFO - +12047861522 test.pdf +12044799001
2022-04-06 15:18:13,989 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): platform.devtest.ringcentral.com:443
2022-04-06 15:18:14,360 - urllib3.connectionpool - DEBUG - https://platform.devtest.ringcentral.com:443 "POST /restapi/oauth/token HTTP/1.1" 200 911
2022-04-06 15:18:14,366 - root - DEBUG - __+12047861522__test.pdf
2022-04-06 15:20:47,410 - main - INFO - +12047861522 test.pdf +12044799001
2022-04-06 15:20:47,412 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): platform.devtest.ringcentral.com:443
2022-04-06 15:20:47,765 - urllib3.connectionpool - DEBUG - https://platform.devtest.ringcentral.com:443 "POST /restapi/oauth/token HTTP/1.1" 200 911
2022-04-06 15:20:47,770 - root - INFO - __+12047861522__test.pdf
2022-04-06 15:26:39,694 - main - INFO - +12047861522 test.pdf +12044799001
2022-04-06 15:26:39,696 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): platform.devtest.ringcentral.com:443
2022-04-06 15:26:40,109 - urllib3.connectionpool - DEBUG - https://platform.devtest.ringcentral.com:443 "POST /restapi/oauth/token HTTP/1.1" 200 911
2022-04-06 15:26:40,115 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): platform.devtest.ringcentral.com:443
2022-04-06 15:26:40,712 - urllib3.connectionpool - DEBUG - https://platform.devtest.ringcentral.com:443 "POST /restapi/v1.0/account/~/extension/~/fax HTTP/1.1" 200 890
2022-04-06 15:26:40,715 - main - CRITICAL - Ring Central Exception occurred
Traceback (most recent call last):
  File "E:\pyfaxrc\apps\pyfaxrc.py", line 55, in <module>
    full_jsonpath = main.rc_confirm(resp)
  File "E:\pyfaxrc\apps\main.py", line 35, in rc_confirm
    f_json = str(datetime.datetime.now().strftime('%Y%m%d_%H%M%S')+'_'+response)
TypeError: can only concatenate str (not "ApiResponse") to str
2022-04-06 15:31:12,878 - main - INFO - +12047861522 test.pdf +12044799001
2022-04-06 15:31:12,880 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): platform.devtest.ringcentral.com:443
2022-04-06 15:31:13,246 - urllib3.connectionpool - DEBUG - https://platform.devtest.ringcentral.com:443 "POST /restapi/oauth/token HTTP/1.1" 200 911
2022-04-06 15:31:13,251 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): platform.devtest.ringcentral.com:443
2022-04-06 15:31:13,806 - urllib3.connectionpool - DEBUG - https://platform.devtest.ringcentral.com:443 "POST /restapi/v1.0/account/~/extension/~/fax HTTP/1.1" 200 890
2022-04-06 15:31:13,808 - main - CRITICAL - Ring Central Exception occurred
Traceback (most recent call last):
  File "E:\pyfaxrc\apps\pyfaxrc.py", line 57, in <module>
    with open(full_jsonpath, 'w+') as f_resp:
OSError: [Errno 22] Invalid argument: 'E:\\pyfaxrc\\apps\\Response\\20220406_153113_E:\\pyfaxrc\\apps\\Response\\20220406_153113_Queued'
2022-04-06 15:33:24,526 - main - INFO - +12047861522 test.pdf +12044799001
2022-04-06 15:33:24,528 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): platform.devtest.ringcentral.com:443
2022-04-06 15:33:24,903 - urllib3.connectionpool - DEBUG - https://platform.devtest.ringcentral.com:443 "POST /restapi/oauth/token HTTP/1.1" 200 911
2022-04-06 15:33:24,908 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): platform.devtest.ringcentral.com:443
2022-04-06 15:33:25,435 - urllib3.connectionpool - DEBUG - https://platform.devtest.ringcentral.com:443 "POST /restapi/v1.0/account/~/extension/~/fax HTTP/1.1" 200 890
2022-04-06 15:33:25,438 - main - CRITICAL - Ring Central Exception occurred
Traceback (most recent call last):
  File "E:\pyfaxrc\apps\pyfaxrc.py", line 57, in <module>
    with open(full_jsonpath, 'w+') as f_resp:
OSError: [Errno 22] Invalid argument: 'E:\\pyfaxrc\\apps\\Response\\20220406_153325_E:\\pyfaxrc\\apps\\Response\\20220406_153325_Queued'
============================================================================================================================================================================
2022-04-06 15:38:44,319 - main - INFO - +12047861522 test.pdf +12044799001
2022-04-06 15:38:44,321 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): platform.devtest.ringcentral.com:443
2022-04-06 15:38:44,701 - urllib3.connectionpool - DEBUG - https://platform.devtest.ringcentral.com:443 "POST /restapi/oauth/token HTTP/1.1" 200 911
2022-04-06 15:38:44,709 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): platform.devtest.ringcentral.com:443
2022-04-06 15:38:45,306 - urllib3.connectionpool - DEBUG - https://platform.devtest.ringcentral.com:443 "POST /restapi/v1.0/account/~/extension/~/fax HTTP/1.1" 200 890
2022-04-06 15:38:45,309 - root - INFO - __+12047861522__test.pdf
2022-04-06 15:49:37,100 - main - INFO - +12047861522 test.pdf +12044799001
2022-04-06 15:49:37,102 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): platform.devtest.ringcentral.com:443
2022-04-06 15:49:37,476 - urllib3.connectionpool - DEBUG - https://platform.devtest.ringcentral.com:443 "POST /restapi/oauth/token HTTP/1.1" 200 911
2022-04-06 15:49:37,484 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): platform.devtest.ringcentral.com:443
2022-04-06 15:49:38,009 - urllib3.connectionpool - DEBUG - https://platform.devtest.ringcentral.com:443 "POST /restapi/v1.0/account/~/extension/~/fax HTTP/1.1" 200 890
2022-04-06 15:49:38,012 - root - INFO - __+12047861522__test.pdf
